Exception in thread Thread-4: Traceback (most recent call last): File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner self.run() File "/usr/lib/python3.6/threading.py", line 864, in run self._target(*self._args, **self._kwargs) File "/home/waix/Scrivania/Reaction-Timer/GUI_Interface/serialConnection.py", line 78, in refreshPortsMenu self.__portMenu() File "/home/waix/Scrivania/Reaction-Timer/GUI_Interface/serialConnection.py", line 101, in __portMenu self.popupMenu = OptionMenu(self.window, self.tkvar, *self.portsList) File "/usr/lib/python3.6/tkinter/__init__.py", line 3465, in __init__ command=_setit(variable, value, callback)) File "/usr/lib/python3.6/tkinter/__init__.py", line 2887, in add_command self.add('command', cnf or kw) File "/usr/lib/python3.6/tkinter/__init__.py", line 2878, in add self._options(cnf, kw)) _tkinter.TclError: invalid command name ".!optionmenu11.menu" Exception in Tkinter callback Traceback (most recent call last): File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__ return self.func(*args) File "./GUI.py", line 274, in __buttonToggle self.__buttonOn() File "./GUI.py", line 294, in __buttonOn self.__timeManage() File "./GUI.py", line 411, in __timeManage self.time_n = Text(self.window) File "/usr/lib/python3.6/tkinter/__init__.py", line 3101, in __init__ Widget.__init__(self, master, 'text', cnf, kw) File "/usr/lib/python3.6/tkinter/__init__.py", line 2299, in __init__ (widgetName, self._w) + extra + self._options(cnf)) _tkinter.TclError: can't invoke "text" command: application has been destroyed pygame 1.9.4 Hello from the pygame community. https://www.pygame.org/contribute.html
